---
title: "Get Started"
format: html
editor: visual
---

If you're still unsure if these resources are right for you or how to use them, we have facilitation support available. 

## Steps to Get Started

### Set up an initial consultation meeting

To schedule an initial consultation meeting, visit this [link](https://calendly.com/victoria-delacruz-chaminade/30min?month=2026-05). 

We ask that you prepare the following prior to the initial meeting:
  - Project/research purpose
  - # of participants in possible workshop
  - Current research/teaching methods and tools
  

### Schedule a workshop for you or your classroom

After the initial consultation meeting, we'll collaborate on workshop or lab material for you and your class to use. From there, we can schedule a time for us to come and run through the material. 

For individual or group researchers, we'll schedule virtual or in-person training sessions to help you best use these resources. 

*Please provide us 2 weeks lead time to prepare classroom workshop materials.*


### Review documentation

Check out this resource for more technical and detailed information on using some of the CI tools. 
